### ISSUE TITLE
[BUG]: Workflow wont always load

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#4525]
**Describe the bug**
When clicking one a few of my workflows I am running into an error.
```
Uncaught TypeError: Cannot read properties of null (reading 'offsetTop')
    at tera-workflow.vue:785:35
    at Array.forEach (<anonymous>)
    at tera-workflow.vue:783:10
    at Proxy.forEach (<anonymous>)
    at relinkEdges (tera-workflow.vue:779:10)
    at resizeHandler (tera-workflow.vue:744:2)
    at callWithErrorHandling (chunk-LDG2OHQ7.js?v=b57a1f43:1731:18)
    at callWithAsyncErrorHandling (chunk-LDG2OHQ7.js?v=b57a1f43:1739:17)
    at emit (chunk-LDG2OHQ7.js?v=b57a1f43:2248:5)
    at chunk-LDG2OHQ7.js?v=b57a1f43:9077:45
```

[response_1724259955237.json](https://github.com/user-attachments/files/16695617/response_1724259955237.json)

There does not appear to be a missing edge in this workflow so as of right now I am not totally sure what is happening

When logging `portElem` [here](https://github.com/DARPA-ASKEM/terarium/blob/main/packages/client/hmi-client/src/components/workflow/tera-workflow.vue#L784) I see it getting null

**Comment by Tom-Szendrey** [comment]
It appears that this was due to one of my simulation nodes having an incorrect state and not containing `chartConfigs`
