### ISSUE TITLE
[BUG]: Simulate with interventions fail

### ISSUE THREAD

**Issue by bigglesandginger** [DARPA-ASKEM/terarium#4548]
- Scenario: Simulate
- Step: 3.2
- Link to the project: https://app.staging.terarium.ai/projects/c5a3cb4b-7a37-4037-9f7b-f893cf206e6a/workflow/1130d6ea-2ff6-4d02-9dad-41c1f33d8f9a?operator=429ec6ac-13a4-40cb-b53f-7fe03fb8b2f7

**Describe the issue**
Fails with 
![Screenshot 2024-08-22 at 2 08 17 PM](https://github.com/user-attachments/assets/dc04c5cf-c8f6-4d9c-a7b7-555a87dbde08)

**Comment by dgauldie** [comment]
can you retest

**Comment by bigglesandginger** [comment]
When running the Simulation this first execution resulted in the following error in pyciemss 

```
2024-08-27T14:45:22.363109514Z AttributeError: 'CompiledDynamics' object has no attribute 'S'
2024-08-27T14:45:22.365200564Z DEBUG:rq.job:Running failure callbacks for e5041cdc-8c2d-4afa-aeac-4723a423a1ed
2024-08-27T14:45:22.365254150Z DEBUG:root:Updating simulation `http://hmi-server:3000/simulations/e5041cdc-8c2d-4afa-aeac-4723a423a1ed` -- error start: False; finish: False; result_files: []
2024-08-27T14:45:22.366136968Z DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hmi-server:3000
2024-08-27T14:45:22.373697132Z DEBUG:urllib3.connectionpool:http://hmi-server:3000 "GET /simulations/e5041cdc-8c2d-4afa-aeac-4723a423a1ed HTTP/1.1" 200 None
2024-08-27T14:45:22.374751294Z DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): hmi-server:3000
2024-08-27T14:45:22.384548838Z DEBUG:urllib3.connectionpool:http://hmi-server:3000 "PUT /simulations/e5041cdc-8c2d-4afa-aeac-4723a423a1ed HTTP/1.1" 200 None
2024-08-27T14:45:22.385417569Z ERROR:root:
2024-08-27T14:45:22.385432216Z         ###############################
2024-08-27T14:45:22.385434658Z
2024-08-27T14:45:22.385441783Z         There was an exception in CIEMSS Service
2024-08-27T14:45:22.385443900Z
2024-08-27T14:45:22.385446968Z         job: e5041cdc-8c2d-4afa-aeac-4723a423a1ed
2024-08-27T14:45:22.385449445Z         <class 'AttributeError'>: 'CompiledDynamics' object has no attribute 'S'
2024-08-27T14:45:22.385451842Z         ################################
2024-08-27T14:45:22.385454139Z
2024-08-27T14:45:22.385456351Z Traceback (most recent call last):
2024-08-27T14:45:22.385458733Z   File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
2024-08-27T14:45:22.385461627Z     rv = job.perform()
2024-08-27T14:45:22.385463987Z   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
2024-08-27T14:45:22.385466448Z     self._result = self._execute()
2024-08-27T14:45:22.385468924Z   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
2024-08-27T14:45:22.385471369Z     result = self.func(*self.args, **self.kwargs)
2024-08-27T14:45:22.385473873Z   File "/service/./execute.py", line 37, in run
2024-08-27T14:45:22.385476426Z     output = eval(operation_name)(**kwargs)
2024-08-27T14:45:22.385479115Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/integration_utils/custom_decorators.py", line 29, in wrapped
2024-08-27T14:45:22.385481604Z     raise e
2024-08-27T14:45:22.385484223Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
2024-08-27T14:45:22.385486758Z     result = function(*args, **kwargs)
2024-08-27T14:45:22.385489282Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 526, in sample
2024-08-27T14:45:22.385491767Z     samples = pyro.infer.Predictive(
2024-08-27T14:45:22.385494562Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
2024-08-27T14:45:22.385497069Z     return self._call_impl(*args, **kwargs)
2024-08-27T14:45:22.385499604Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
2024-08-27T14:45:22.385502042Z     return forward_call(*args, **kwargs)
2024-08-27T14:45:22.385504478Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 273, in forward
2024-08-27T14:45:22.385507063Z     return _predictive(
2024-08-27T14:45:22.385509483Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 127, in _predictive
2024-08-27T14:45:22.385512164Z     return _predictive_sequential(
2024-08-27T14:45:22.385514673Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 48, in _predictive_sequential
2024-08-27T14:45:22.385517192Z     trace = poutine.trace(poutine.condition(model, samples[i])).get_trace(
2024-08-27T14:45:22.385519664Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
2024-08-27T14:45:22.385522556Z     self(*args, **kwargs)
2024-08-27T14:45:22.385525033Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
2024-08-27T14:45:22.385527480Z     ret = self.fn(*args, **kwargs)
2024-08-27T14:45:22.385529989Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
2024-08-27T14:45:22.385532493Z     return fn(*args, **kwargs)
2024-08-27T14:45:22.385534953Z   File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
2024-08-27T14:45:22.385537402Z     return func(*args, **kwargs)
2024-08-27T14:45:22.385540017Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
2024-08-27T14:45:22.385549733Z     return fn(*args, **kwargs)
2024-08-27T14:45:22.385552296Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 499, in wrapped_model
2024-08-27T14:45:22.385554771Z     full_trajectory = model(
2024-08-27T14:45:22.385557140Z   File "/usr/local/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
2024-08-27T14:45:22.385559481Z     result = super().__call__(*args, **kwargs)
2024-08-27T14:45:22.385561646Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
2024-08-27T14:45:22.385564210Z     return self._call_impl(*args, **kwargs)
2024-08-27T14:45:22.385566525Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
2024-08-27T14:45:22.385569515Z     return forward_call(*args, **kwargs)
2024-08-27T14:45:22.385571393Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/compiled_dynamics.py", line 126, in forward
2024-08-27T14:45:22.385572938Z     simulate(self.deriv, self.initial_state(), start_time, end_time)
2024-08-27T14:45:22.385574393Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 281, in _fn
2024-08-27T14:45:22.385575816Z     apply_stack(msg)
2024-08-27T14:45:22.385577271Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 212, in apply_stack
2024-08-27T14:45:22.385578711Z     frame._process_message(msg)
2024-08-27T14:45:22.385582176Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 162, in _process_message
2024-08-27T14:45:22.385584417Z     return method(msg)
2024-08-27T14:45:22.385586734Z   File "/usr/local/lib/python3.10/site-packages/chirho/dynamical/internals/solver.py", line 119, in _pyro_simulate
2024-08-27T14:45:22.385589213Z     dynamics, state = next_interruption.callback(dynamics, state)
2024-08-27T14:45:22.385592805Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interruptions.py", line 85, in callback
2024-08-27T14:45:22.385597456Z     old_parameter = getattr(dynamics_obj, parameter_name)
2024-08-27T14:45:22.385606553Z   File "/usr/local/lib/python3.10/site-packages/pyro/nn/module.py", line 531, in __getattr__
2024-08-27T14:45:22.385609227Z     result = super().__getattr__(name)
2024-08-27T14:45:22.385612149Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
2024-08-27T14:45:22.385613720Z     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
2024-08-27T14:45:22.385615376Z AttributeError: 'CompiledDynamics' object has no attribute 'S'
2024-08-27T14:45:22.388909611Z 14:45:22 [Job e5041cdc-8c2d-4afa-aeac-4723a423a1ed]: exception raised while executing (execute.run)
2024-08-27T14:45:22.388920055Z Traceback (most recent call last):
2024-08-27T14:45:22.388922588Z   File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
2024-08-27T14:45:22.388924895Z     rv = job.perform()
2024-08-27T14:45:22.388926853Z   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
2024-08-27T14:45:22.388928956Z     self._result = self._execute()
2024-08-27T14:45:22.388930964Z   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
2024-08-27T14:45:22.388933195Z     result = self.func(*self.args, **self.kwargs)
2024-08-27T14:45:22.388935224Z   File "/service/./execute.py", line 37, in run
2024-08-27T14:45:22.388937106Z     output = eval(operation_name)(**kwargs)
2024-08-27T14:45:22.388939276Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/integration_utils/custom_decorators.py", line 29, in wrapped
2024-08-27T14:45:22.388944444Z     raise e
2024-08-27T14:45:22.388946786Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
2024-08-27T14:45:22.388949554Z     result = function(*args, **kwargs)
2024-08-27T14:45:22.388951875Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 526, in sample
2024-08-27T14:45:22.388954136Z     samples = pyro.infer.Predictive(
2024-08-27T14:45:22.388956319Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
2024-08-27T14:45:22.388958344Z     return self._call_impl(*args, **kwargs)
2024-08-27T14:45:22.388960399Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
2024-08-27T14:45:22.388962379Z     return forward_call(*args, **kwargs)
2024-08-27T14:45:22.388964450Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 273, in forward
2024-08-27T14:45:22.388966712Z     return _predictive(
2024-08-27T14:45:22.388969193Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 127, in _predictive
2024-08-27T14:45:22.388971382Z     return _predictive_sequential(
2024-08-27T14:45:22.388973556Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 48, in _predictive_sequential
2024-08-27T14:45:22.388976399Z     trace = poutine.trace(poutine.condition(model, samples[i])).get_trace(
2024-08-27T14:45:22.388978662Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
2024-08-27T14:45:22.388981130Z     self(*args, **kwargs)
2024-08-27T14:45:22.388983266Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
2024-08-27T14:45:22.388985160Z     ret = self.fn(*args, **kwargs)
2024-08-27T14:45:22.388987266Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
2024-08-27T14:45:22.388989263Z     return fn(*args, **kwargs)
2024-08-27T14:45:22.388991553Z   File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
2024-08-27T14:45:22.388993473Z     return func(*args, **kwargs)
2024-08-27T14:45:22.388995766Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
2024-08-27T14:45:22.388997789Z     return fn(*args, **kwargs)
2024-08-27T14:45:22.389000707Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 499, in wrapped_model
2024-08-27T14:45:22.389002860Z     full_trajectory = model(
2024-08-27T14:45:22.389007119Z   File "/usr/local/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
2024-08-27T14:45:22.389009095Z     result = super().__call__(*args, **kwargs)
2024-08-27T14:45:22.389011503Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
2024-08-27T14:45:22.389013613Z     return self._call_impl(*args, **kwargs)
2024-08-27T14:45:22.389015835Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
2024-08-27T14:45:22.389018173Z     return forward_call(*args, **kwargs)
2024-08-27T14:45:22.389020350Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/compiled_dynamics.py", line 126, in forward
2024-08-27T14:45:22.389023012Z     simulate(self.deriv, self.initial_state(), start_time, end_time)
2024-08-27T14:45:22.389025226Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 281, in _fn
2024-08-27T14:45:22.389027233Z     apply_stack(msg)
2024-08-27T14:45:22.389029430Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 212, in apply_stack
2024-08-27T14:45:22.389042008Z     frame._process_message(msg)
2024-08-27T14:45:22.389044411Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 162, in _process_message
2024-08-27T14:45:22.389046405Z     return method(msg)
2024-08-27T14:45:22.389048861Z   File "/usr/local/lib/python3.10/site-packages/chirho/dynamical/internals/solver.py", line 119, in _pyro_simulate
2024-08-27T14:45:22.389050856Z     dynamics, state = next_interruption.callback(dynamics, state)
2024-08-27T14:45:22.389053199Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interruptions.py", line 85, in callback
2024-08-27T14:45:22.389055073Z     old_parameter = getattr(dynamics_obj, parameter_name)
2024-08-27T14:45:22.389057219Z   File "/usr/local/lib/python3.10/site-packages/pyro/nn/module.py", line 531, in __getattr__
2024-08-27T14:45:22.389059211Z     result = super().__getattr__(name)
2024-08-27T14:45:22.389061260Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
2024-08-27T14:45:22.389068833Z     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
2024-08-27T14:45:22.389071157Z AttributeError: 'CompiledDynamics' object has no attribute 'S'
2024-08-27T14:45:22.389073224Z
2024-08-27T14:45:22.389075425Z ERROR:rq.worker:[Job e5041cdc-8c2d-4afa-aeac-4723a423a1ed]: exception raised while executing (execute.run)
2024-08-27T14:45:22.389077673Z Traceback (most recent call last):
2024-08-27T14:45:22.389080053Z   File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job
2024-08-27T14:45:22.389082056Z     rv = job.perform()
2024-08-27T14:45:22.389084559Z   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1278, in perform
2024-08-27T14:45:22.389087082Z     self._result = self._execute()
2024-08-27T14:45:22.389089467Z   File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute
2024-08-27T14:45:22.389091984Z     result = self.func(*self.args, **self.kwargs)
2024-08-27T14:45:22.389094644Z   File "/service/./execute.py", line 37, in run
2024-08-27T14:45:22.389096853Z     output = eval(operation_name)(**kwargs)
2024-08-27T14:45:22.389098957Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/integration_utils/custom_decorators.py", line 29, in wrapped
2024-08-27T14:45:22.389101446Z     raise e
2024-08-27T14:45:22.389103895Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/integration_utils/custom_decorators.py", line 10, in wrapped
2024-08-27T14:45:22.389106213Z     result = function(*args, **kwargs)
2024-08-27T14:45:22.389108718Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 526, in sample
2024-08-27T14:45:22.389111237Z     samples = pyro.infer.Predictive(
2024-08-27T14:45:22.389114759Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
2024-08-27T14:45:22.389117410Z     return self._call_impl(*args, **kwargs)
2024-08-27T14:45:22.389124076Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
2024-08-27T14:45:22.389126893Z     return forward_call(*args, **kwargs)
2024-08-27T14:45:22.389132405Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 273, in forward
2024-08-27T14:45:22.389135155Z     return _predictive(
2024-08-27T14:45:22.389137798Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 127, in _predictive
2024-08-27T14:45:22.389140890Z     return _predictive_sequential(
2024-08-27T14:45:22.389144148Z   File "/usr/local/lib/python3.10/site-packages/pyro/infer/predictive.py", line 48, in _predictive_sequential
2024-08-27T14:45:22.389153293Z     trace = poutine.trace(poutine.condition(model, samples[i])).get_trace(
2024-08-27T14:45:22.389155906Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 198, in get_trace
2024-08-27T14:45:22.389159508Z     self(*args, **kwargs)
2024-08-27T14:45:22.389162473Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/trace_messenger.py", line 174, in __call__
2024-08-27T14:45:22.389165337Z     ret = self.fn(*args, **kwargs)
2024-08-27T14:45:22.389168016Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
2024-08-27T14:45:22.389170606Z     return fn(*args, **kwargs)
2024-08-27T14:45:22.389173805Z   File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
2024-08-27T14:45:22.389176479Z     return func(*args, **kwargs)
2024-08-27T14:45:22.389182555Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 12, in _context_wrap
2024-08-27T14:45:22.389185362Z     return fn(*args, **kwargs)
2024-08-27T14:45:22.389188178Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 499, in wrapped_model
2024-08-27T14:45:22.389193737Z     full_trajectory = model(
2024-08-27T14:45:22.389196495Z   File "/usr/local/lib/python3.10/site-packages/pyro/nn/module.py", line 449, in __call__
2024-08-27T14:45:22.389199428Z     result = super().__call__(*args, **kwargs)
2024-08-27T14:45:22.389205000Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
2024-08-27T14:45:22.389207602Z     return self._call_impl(*args, **kwargs)
2024-08-27T14:45:22.389210773Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
2024-08-27T14:45:22.389216393Z     return forward_call(*args, **kwargs)
2024-08-27T14:45:22.389219430Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/compiled_dynamics.py", line 126, in forward
2024-08-27T14:45:22.389222357Z     simulate(self.deriv, self.initial_state(), start_time, end_time)
2024-08-27T14:45:22.389224989Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 281, in _fn
2024-08-27T14:45:22.389228103Z     apply_stack(msg)
2024-08-27T14:45:22.389231079Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/runtime.py", line 212, in apply_stack
2024-08-27T14:45:22.389233742Z     frame._process_message(msg)
2024-08-27T14:45:22.389236774Z   File "/usr/local/lib/python3.10/site-packages/pyro/poutine/messenger.py", line 162, in _process_message
2024-08-27T14:45:22.389239592Z     return method(msg)
2024-08-27T14:45:22.389242642Z   File "/usr/local/lib/python3.10/site-packages/chirho/dynamical/internals/solver.py", line 119, in _pyro_simulate
2024-08-27T14:45:22.389245334Z     dynamics, state = next_interruption.callback(dynamics, state)
2024-08-27T14:45:22.389248106Z   File "/usr/local/lib/python3.10/site-packages/pyciemss/interruptions.py", line 85, in callback
2024-08-27T14:45:22.389250944Z     old_parameter = getattr(dynamics_obj, parameter_name)
2024-08-27T14:45:22.389266005Z   File "/usr/local/lib/python3.10/site-packages/pyro/nn/module.py", line 531, in __getattr__
2024-08-27T14:45:22.389271773Z     result = super().__getattr__(name)
2024-08-27T14:45:22.389274682Z   File "/usr/local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
2024-08-27T14:45:22.389277330Z     raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
2024-08-27T14:45:22.389280009Z AttributeError: 'CompiledDynamics' object has no attribute 'S'
2024-08-27T14:45:22.389282051Z
```

But rerunning completed correctly (on a different worker)

**Comment by bigglesandginger** [comment]
![Image](https://github.com/user-attachments/assets/9b925b54-8c01-4a5e-94a7-36fe8d650016)

**Comment by Tom-Szendrey** [comment]
Note:
What is happening in simulate here may also occur in optimize and calibrate.
The issue here is that we have a dynamic intervention on a state. 
If/When this intervention triggers pyciemss will fail to find the intervention's state S as it expects interventions on parameters 

This only occurs some of the times as the intervention used is dynamic and only triggers WHEN X occurs and X does not always occur. To make this fail more change num samples to higher number, to make this pass more change num of samples to lower.

https://app.staging.terarium.ai/projects/c5a3cb4b-7a37-4037-9f7b-f893cf206e6a/workflow/c1a26e7a-515e-4a3f-8401-130426fbfa4c

**Comment by Tom-Szendrey** [comment]
Issue here is that the converters in pyciemss-service throw everything into the static_**parameter**_interventions while they should create a second static_**state**_interventions

```
static_state_interventions: Dict[torch.Tensor, Dict[str, Intervention]] = {},
static_parameter_interventions: Dict[torch.Tensor, Dict[str, Intervention]] = {},
```
