### ISSUE TITLE
[BUG]: Stratify model node disconnection

### ISSUE THREAD

**Issue by blanchco** [DARPA-ASKEM/terarium#4689]
- Scenario: Model configuration
- Step: 5.2/5.3
- Link to the project: https://app.staging.terarium.ai/projects/9cbe3e3d-e40b-44b4-a3c4-316b7edcae2d/workflow/78196fd2-de11-4f39-9087-70f8b48e1ced

**Describe the issue**
After running a stratify specifically, the node seems to be unmovable

```
TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (main-C5eSF_dj.js:20:63970)
    at hu (main-C5eSF_dj.js:20:49112)
    at du (main-C5eSF_dj.js:20:48748)
    at Us (main-C5eSF_dj.js:20:44674)
    at lu (main-C5eSF_dj.js:20:47828)
    at au (main-C5eSF_dj.js:20:47000)
    at tu (main-C5eSF_dj.js:20:45416)
    at Us (main-C5eSF_dj.js:20:44638)
    at ReactiveEffect.jp [as fn] (main-C5eSF_dj.js:20:49787)
    at ReactiveEffect.run (main-C5eSF_dj.js:9:1934)
```

https://github.com/user-attachments/assets/2c0f213d-9219-4d03-a26c-ae382652be71

**Comment by mwdchang** [comment]
This looks like it is closely related to https://github.com/DARPA-ASKEM/terarium/issues/4780 which reported the same "emitsOptions" errors and syncing problems. 

Specifically with stratify, there is a gap-window when stratify is completed where we should synchronize two long-operations. The fix had been done here: https://github.com/DARPA-ASKEM/terarium/pull/4801
