### ISSUE TITLE
[BUG]: Post stratification error

### ISSUE THREAD

**Issue by mwdchang** [DARPA-ASKEM/terarium#4780]
Stratification seemed to work, but we don't seem to handle the result properly?

The console is showing several of these errors

```
TypeError: Cannot read properties of null (reading 'emitsOptions')
    at shouldUpdateComponent (main-AwGyjmr-.js:20:50562)
    at hu (main-AwGyjmr-.js:20:36548)
    at du (main-AwGyjmr-.js:20:36184)
    at Us (main-AwGyjmr-.js:20:32110)
    at uu (main-AwGyjmr-.js:20:35264)
    at au (main-AwGyjmr-.js:20:34436)
    at tu (main-AwGyjmr-.js:20:32852)
    at Us (main-AwGyjmr-.js:20:32074)
    at ReactiveEffect.jp [as fn] (main-AwGyjmr-.js:20:37223)
    at ReactiveEffect.run (main-AwGyjmr-.js:9:1934)
```

While the "save-for-reuse" button became available and then greyed out without any user intervention, also it seemed like the operation run did not result in a new "output" for the operator.

**Comment by mwdchang** [comment]
This is a workflow sync issue. An attempt to resolve is in this PR https://github.com/DARPA-ASKEM/terarium/pull/4801
