### ISSUE TITLE
[BUG]: 500 errors on startup

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#4787]
- Scenario:
- Step:
- Link to the project:

**Describe the issue**

![image](https://github.com/user-attachments/assets/4a95ccdf-9d28-4de9-a7d2-a0b239167798)

**Comment by mwdchang** [comment]
This came from the notifications, with the log trace

```
2024-09-20 18:20:20 [INFO] REQUEST STARTED | ModelController.getModel | method=GET; uri=/models/33f73bce-38ee-45c5-93d0-6e672767253c;  [software.uncharted.terarium.hmiserver.interceptors.RequestLoggingInterceptor:40]
2024-09-20 18:20:20 [ERROR] Unable to get model [software.uncharted.terarium.hmiserver.controller.dataservice.ModelController:239]
org.springframework.web.server.ResponseStatusException: 403 FORBIDDEN "You're not authorized to access this resource. Contact the project owner to upgrade your permissions."
	at software.uncharted.terarium.hmiserver.controller.dataservice.ModelController.getModel(ModelController.java:170)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
```
