### ISSUE TITLE
[BUG]: Cannot Save Dataset from Data Transform (does not appear in my list of saved datasets)

### ISSUE THREAD

**Issue by hvasque14** [DARPA-ASKEM/terarium#4890]
I need to be able to use the data transform operator to save a dataset I create. When I use the data transform operator and calculate average hospitalizations, I can save this as a new dataset. However, this new dataset does not appear in my list of saved datasets. 

https://github.com/user-attachments/assets/36a3b385-cee3-48dc-ae80-43921a684467

**Comment by mwdchang** [comment]
Saw this error in the beaker logs, looks like we should check if "description" exist

```
KeyError: 'description'
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/jupyter/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 575, in _log_error
    f.result()
  File "/home/jupyter/.local/lib/python3.10/site-packages/beaker_kernel/lib/jupyter_kernel_proxy.py", line 253, in handler
    new_data = await callback(self, other_stream, data)
  File "/home/jupyter/.local/lib/python3.10/site-packages/beaker_kernel/lib/utils.py", line 103, in wrapper
    result = await fn(self, ctx.message)
  File "/home/jupyter/.local/lib/python3.10/site-packages/askem_beaker/contexts/dataset/context.py", line 237, in save_dataset_request
    new_dataset["description"] += f"\\nTransformed from dataset '{parent_dataset['name']}' ({parent_dataset['id']}) at {datetime.datetime.utcnow().strftime('%c %Z')}"
KeyError: 'description'
Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/home/jupyter/.local/lib/python3.10/site-packages/zmq/eventloop/zmqstream.py", line 575, in _log_error
    f.result()
  File "/home/jupyter/.local/lib/python3.10/site-packages/beaker_kernel/lib/jupyter_kernel_proxy.py", line 253, in handler
    new_data = await callback(self, other_stream, data)
  File "/home/jupyter/.local/lib/python3.10/site-packages/beaker_kernel/lib/utils.py", line 103, in wrapper
    result = await fn(self, ctx.message)
  File "/home/jupyter/.local/lib/python3.10/site-packages/askem_beaker/contexts/dataset/context.py", line 237, in save_dataset_request
    new_dataset["description"] += f"\\nTransformed from dataset '{parent_dataset['name']}' ({parent_dataset['id']}) at {datetime.datetime.utcnow().strftime('%c %Z')}"
KeyError: 'description'
```
