### ISSUE TITLE
[BUG]: calibrate operator state and output not saved

### ISSUE THREAD

**Issue by shawnyama** [DARPA-ASKEM/terarium#5284]
**Describe the bug**
My state and outputs were not saved once I reopened my workflow in a separate tab.

**To Reproduce**
1. Follow the calibrate steps https://github.com/DARPA-ASKEM/terarium/blob/main/testing/manual/calibrate.md
2. Once you have an output copy the url you are on and open it in another tab
3. Notice that the operator is empty

Here is a console error I notice when opening the calibrate drilldown in my first tab. Not sure if it is related
```
ERROR TypeError: rt[Dr] is not a function
    at main-CNm8pmyx.js:3540:58029
    at Array.forEach (<anonymous>)
    at visitArray (main-CNm8pmyx.js:3539:10014)
    at Pulse.visit (main-CNm8pmyx.js:3540:13636)
    at Fold.transform (main-CNm8pmyx.js:3540:57941)
    at Fold.evaluate (main-CNm8pmyx.js:3540:19274)
    at Fold.run (main-CNm8pmyx.js:3540:19131)
    at View$1.evaluate (main-CNm8pmyx.js:3540:15482)
    at View$1.evaluate (main-CNm8pmyx.js:3547:2406)
    at View$1.runAsync (main-CNm8pmyx.js:3540:16244)
```

**Expected behavior**
The same state and output as the previous tab should be in the new one.

**Video showing the issue**
https://github.com/user-attachments/assets/2d54987d-f0ff-41eb-898a-bedcd5ed41e6

**Comment by mwdchang** [comment]
I cannot reproduce this - the possible cause might be the javascript errors that were fixed in https://github.com/DARPA-ASKEM/terarium/pull/5277 these errors were making the application unpredictable.
