### ISSUE TITLE
Optimize new value and start time bug

### ISSUE THREAD

**Issue by Tom-Szendrey** [DARPA-ASKEM/terarium#5321]
When trying to optimize with new value and start time we get an index out of range error.

`Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/rq/worker.py", line 1428, in perform_job rv = job.perform() File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1278, in perform self._result = self._execute() File "/usr/local/lib/python3.10/site-packages/rq/job.py", line 1315, in _execute result = self.func(*self.args, **self.kwargs) File "/service/./execute.py", line 33, in run output = eval(operation_name)(**kwargs) File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 982, in optimize ).solve() File "/usr/local/lib/python3.10/site-packages/pyciemss/ouu/ouu.py", line 219, in solve result = basinhopping( File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_basinhopping.py", line 714, in basinhopping bh = BasinHoppingRunner(x0, wrapped_minimizer, take_step_wrapped, File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_basinhopping.py", line 78, in __init__ minres = minimizer(self.x) File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_basinhopping.py", line 302, in __call__ return self.minimizer(self.func, x0, **self.kwargs) File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_minimize.py", line 737, in minimize res = _minimize_cobyla(fun, x0, args, constraints, callback=callback, File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 35, in wrapper return func(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_cobyla_py.py", line 278, in _minimize_cobyla sf = _prepare_scalar_function(fun, x0, args=args, jac=_jac) File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_optimize.py", line 288, in _prepare_scalar_function sf = ScalarFunction(fun, x0, args, grad, hess, File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 222, in __init__ self._update_fun() File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 294, in _update_fun fx = self._wrapped_fun(self.x) File "/usr/local/lib/python3.10/site-packages/scipy/optimize/_differentiable_functions.py", line 20, in wrapped fx = fun(np.copy(x), *args) File "/usr/local/lib/python3.10/site-packages/pyciemss/interfaces.py", line 969, in objfun_penalty return objfun(x) + max(5 * np.abs(objfun(x)), 5.0) File "/service/./models/operations/optimize.py", line 239, in <lambda> "objfun": lambda x: objfun( File "/service/./models/operations/optimize.py", line 96, in objfun weight = relative_importance[i] / sum_of_all_weights IndexError: list index out of range
`

**Comment by Tom-Szendrey** [comment]
Just keepings notes on why this is happening:
We have written out obj function lamda to be such that 

- x
- initial_guess
- objective_function_option
- relative_importance

All have the same length. The issue with that is that x is the amount of variables being optimized over and our relative_importance is the amount of interventions we have
In this picture we have 1 relative importance of 5, but we have two variables being optimized over. beta's value and beta's time.
![Image](https://github.com/user-attachments/assets/738362f1-085c-475f-8944-63a971f4489f)

**Comment by Tom-Szendrey** [comment]
This has been finished with 
https://github.com/DARPA-ASKEM/terarium/pull/5360
https://github.com/DARPA-ASKEM/pyciemss-service/pull/124
https://github.com/DARPA-ASKEM/pyciemss-service/pull/125
