### ISSUE TITLE
[BUG]: Dataset enrichment fails

### ISSUE THREAD

**Issue by dgauldie** [DARPA-ASKEM/terarium#5346]
- Scenario: dataset-enrichment
- Step: 3.2
- Link to the project: https://app.staging.terarium.ai/projects/17086c53-c727-4607-a0b1-e661aed048b9/dataset/1b427659-92e4-4eab-9c2e-9b232466c780

**Describe the issue**

![Image](https://github.com/user-attachments/assets/e8622d6c-91ed-49d6-ad0a-487777ae0002)

The error on MIT-TR says
```
csv_file head (first 10 lines):
t,s,i,r
0.0,0.99995,5E-05,0.0
0.9045226130653270,0.9999360401998250,5.81428837853521E-05,5.81691638943948E-06
1.8090452261306500,0.9999198054491840,6.76126650732997E-05,1.25818857422612E-05
2.71356783919598,0.9999009552059880,7.86079359487088E-05,2.0436858062973E-05
3.6180904522613100,0.9998790332211640,9.13947540566949E-05,2.95720247796426E-05
4.522613065326630,0.9998535367124580,0.00010626629350235700,4.01969940395947E-05
5.42713567839196,0.9998238896238350,0.00012355843011929300,5.25519460459022E-05
6.331658291457290,0.9997894229731460,0.00014366119260970200,6.69158342437095E-05
7.236180904522610,0.9997493586250260,0.00016702820812934200,8.3613166845046E-05
doc_file head (first 5 lines):
There is no documentation for this dataset
Using GPT model:  gpt-4-1106-preview

DESCRIPTION: UNKNOWN
AUTHOR_NAME: UNKNOWN
AUTHOR_EMAIL: UNKNOWN
DATE: UNKNOWN
PROVENANCE: UNKNOWN
SENSITIVITY: UNKNOWN
LICENSE: UNKNOWN

Getting stats
Using GPT model:  gpt-4-1106-preview
Got match

t | Time | Days | The time variable, likely representing the number of days since the beginning of an observation or experiment.
s | Susceptible | Proportion | The proportion of the population that is susceptible to an infection or condition.
i | Infected | Proportion | The proportion of the population that is currently infected with an infection or condition.
r | Recovered | Proportion | The proportion of the population that has recovered from an infection or condition.

building retriever from scratch
INFO:     10.244.17.19:35750 - "POST /cards/get_data_card?gpt_key HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
```

They are using gpt-4-1106-preview. is that deprecated?

**Comment by YohannParis** [comment]
Fixed by @brandomr https://github.com/DARPA-ASKEM/mit-service/pull/4
